# Generated by Django 6.0.3 on 2026-03-05 12:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("correu", models.EmailField(max_length=254, unique=True)),
                ("contrasenya", models.CharField(max_length=128)),
                (
                    "tipus",
                    models.CharField(
                        choices=[
                            ("regular", "Regular User"),
                            ("organizer", "Organizer User"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegularUsuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuari",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.usuari",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[
                            ("ca", "Catalan"),
                            ("es", "Spanish"),
                            ("en", "English"),
                        ],
                        default="ca",
                        max_length=2,
                    ),
                ),
                (
                    "tipusUnitats",
                    models.CharField(
                        choices=[("metric", "Metric"), ("imperial", "Imperial")],
                        default="metric",
                        max_length=20,
                    ),
                ),
                (
                    "aparenca",
                    models.CharField(
                        choices=[
                            ("clar", "Clar"),
                            ("fosc", "Fosc"),
                            ("dispositiu", "Dispositiu"),
                            ("daltonic", "Daltonic"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "usuari",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.usuari",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcio", models.TextField(blank=True)),
                (
                    "punts",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "nFestes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "diesRatxa",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("ultimaFesta", models.DateTimeField(blank=True, null=True)),
                (
                    "usuari",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.usuari",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganitzadorUsuari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarifa",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dataExpiracio", models.DateTimeField(blank=True, null=True)),
                (
                    "usuari",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.usuari",
                    ),
                ),
            ],
        ),
    ]
