# Generated by Django 6.0.3 on 2026-03-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuari",
            name="correuverificat",
            field=models.BooleanField(default=False),
        ),
    ]
